package logging

import (
	"log/slog"
	"sort"
	"strconv"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

// maxProtoDepth bounds recursion. The wire contract nests three deep at most,
// but protobuf messages can be mutually recursive and a logger is the wrong
// place to discover that.
const maxProtoDepth = 8

// Proto renders a protobuf message for logging with credential-bearing fields
// replaced by Placeholder.
//
// This exists because Redact cannot help here. It is a key-based control: it
// sees the attribute key "request", not the enrollment token inside the value
// under it. Every type generated by protoc-gen-go implements String(), which
// renders every field, so slog.Any("request", req) and fmt.Errorf("%v", grant)
// both put a secret in a log or an error string with nothing in the pipeline
// able to intervene.
//
// [debug_redact = true] in the contract does not prevent that either:
// protobuf-go v1.36.6 consults the option nowhere in its own encoding path. The
// marker is machine-readable intent, and this function is the code that acts on
// it. .github/scripts/check_secret_logging.py is what stops a caller reaching
// past both.
//
// Two rules decide what is withheld, and a field matching either is replaced:
//
//   - the field is marked [debug_redact = true] in the contract, or
//   - its name is credential-shaped by IsSensitiveKey, the same test Redact
//     applies to attribute keys.
//
// The second rule is what makes a secret field added to the contract without a
// marker still come out redacted here. The two agreeing also means a field is
// not readable through Proto and redacted through slog.String, or the reverse.
//
// Bytes fields are rendered as a length and never as content. A CSR, a signed
// certificate, an evidence payload and a raw secret are all bytes on this
// contract, and the length is the only part of any of them worth logging.
func Proto(m proto.Message) slog.Value {
	if m == nil {
		return slog.StringValue("<nil>")
	}
	rm := m.ProtoReflect()
	if !rm.IsValid() {
		return slog.StringValue("<nil>")
	}
	return protoValue(rm, 0)
}

// ProtoAttr is Proto as an attribute, which is how callers normally want it:
//
//	slog.Info("dispatching credential", logging.ProtoAttr("grant", grant))
func ProtoAttr(key string, m proto.Message) slog.Attr {
	return slog.Attr{Key: key, Value: Proto(m)}
}

// protoValue renders the populated fields of m in field-number order. Range
// visits only populated fields and in no defined order, and a log line whose
// key order moves between runs cannot be diffed.
func protoValue(m protoreflect.Message, depth int) slog.Value {
	if depth >= maxProtoDepth {
		return slog.StringValue("<max depth>")
	}

	type numbered struct {
		number protoreflect.FieldNumber
		attr   slog.Attr
	}

	var fields []numbered
	m.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		fields = append(fields, numbered{number: fd.Number(), attr: fieldAttr(fd, v, depth)})
		return true
	})
	sort.Slice(fields, func(i, j int) bool { return fields[i].number < fields[j].number })

	attrs := make([]slog.Attr, 0, len(fields))
	for _, f := range fields {
		attrs = append(attrs, f.attr)
	}
	return slog.GroupValue(attrs...)
}

func fieldAttr(fd protoreflect.FieldDescriptor, v protoreflect.Value, depth int) slog.Attr {
	name := string(fd.Name())
	if isRedacted(fd) {
		return slog.String(name, Placeholder)
	}

	switch {
	case fd.IsMap():
		value := fd.MapValue()
		var entries []slog.Attr
		v.Map().Range(func(k protoreflect.MapKey, val protoreflect.Value) bool {
			entries = append(entries, slog.Attr{Key: k.String(), Value: singular(value, val, depth)})
			return true
		})
		sort.Slice(entries, func(i, j int) bool { return entries[i].Key < entries[j].Key })
		return slog.Attr{Key: name, Value: slog.GroupValue(entries...)}

	case fd.IsList():
		list := v.List()
		entries := make([]slog.Attr, 0, list.Len())
		for i := 0; i < list.Len(); i++ {
			entries = append(entries, slog.Attr{Key: strconv.Itoa(i), Value: singular(fd, list.Get(i), depth)})
		}
		return slog.Attr{Key: name, Value: slog.GroupValue(entries...)}

	default:
		return slog.Attr{Key: name, Value: singular(fd, v, depth)}
	}
}

func singular(fd protoreflect.FieldDescriptor, v protoreflect.Value, depth int) slog.Value {
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return protoValue(v.Message(), depth+1)

	case protoreflect.BytesKind:
		return slog.StringValue(strconv.Itoa(len(v.Bytes())) + " bytes")

	case protoreflect.EnumKind:
		// By name, so an operator reading a log does not have to hold the
		// contract's numbering in their head. An unknown number is a scan point
		// newer than this build (ADR-022) and is shown as the number.
		if ev := fd.Enum().Values().ByNumber(v.Enum()); ev != nil {
			return slog.StringValue(string(ev.Name()))
		}
		return slog.StringValue(strconv.FormatInt(int64(v.Enum()), 10))

	default:
		return slog.AnyValue(v.Interface())
	}
}

// isRedacted reports whether a field's value must be withheld: marked in the
// contract, or credential-shaped by the same test Redact applies to keys.
//
// The marker binds whatever the field's type: an author who marks a message
// field means the whole subtree.
//
// The name heuristic is narrower -- it applies only to fields rendered as a
// leaf. A message field is descended into instead, so every scalar inside gets
// both checks on its own. CoreMessage.credential is the case that matters:
// collapsing it on its field name would withhold grant_id, job_id,
// expires_unix and scope, which are exactly the fields ADR-020's audit trail
// wants, while gaining nothing over the per-leaf checks -- material is marked,
// and any future secret leaf must be marked and added to SECRET_FIELDS, which
// .github/scripts/check_secret_logging.py enforces in both directions. A
// redactor that hides the whole message an implementer is debugging is one they
// route around.
func isRedacted(fd protoreflect.FieldDescriptor) bool {
	if opts, ok := fd.Options().(*descriptorpb.FieldOptions); ok && opts.GetDebugRedact() {
		return true
	}
	if isMessageField(fd) {
		return false
	}
	return IsSensitiveKey(string(fd.Name()))
}

// isMessageField reports whether the field is descended into rather than
// rendered as a leaf. A map is excluded: its own name is the meaningful one,
// its entry type is a synthesised message, and its values are rendered as
// leaves.
func isMessageField(fd protoreflect.FieldDescriptor) bool {
	if fd.IsMap() {
		return false
	}
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return true
	default:
		return false
	}
}
