package ca

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// GenerateSelfSigned writes a self-signed CA certificate and key to dir.
//
// TWO legitimate uses, and one illegitimate one worth naming.
//
// Legitimate: tests, and bootstrapping an on-prem or air-gapped deployment that
// has no PKI of its own. ADR-018 rejected a public CA precisely because
// air-gapped deployments exist and cannot reach one, so something has to be able
// to make a root locally.
//
// Illegitimate: SaaS. Our SaaS CA is not generated by the application at
// startup; it is provisioned, backed up, and its key is held where an operator
// decides. A Core that quietly generates a CA when it finds no key configured
// would produce a fleet whose trust anchor changes on every restart, and every
// scan point would fail to authenticate with nothing saying why. So this
// function is never called from Open, never called from a default, and never
// called without an operator asking for it — Open returns ErrNotConfigured
// instead.
//
// The key is written 0600 and the directory 0700, matching what Open will refuse
// to load without.
func GenerateSelfSigned(dir, commonName string, validFor time.Duration) (certPath, keyPath string, err error) {
	// MkdirAll leaves an existing directory's mode alone, so 0700 here applies
	// only when this call creates it.
	//
	// There is deliberately no assertion on the directory's mode. A single
	// directory's permissions do not answer the question: t.TempDir produces a
	// 0775 leaf inside a 0700 parent, which is unreachable by others and would
	// fail such a check, while a 0700 leaf inside a world-writable parent would
	// pass one and be reachable. Answering properly means walking every
	// ancestor, and a check that is wrong in both directions is worse than none.
	//
	// The control is O_EXCL in writeNew below: it refuses to write through a
	// symlink, and refuses to write at all if the file already exists — so an
	// attacker who pre-creates ca.key in a writable directory causes a loud
	// failure rather than a substituted key.
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", "", fmt.Errorf("ca: create dir: %w", err)
	}

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return "", "", fmt.Errorf("ca: generate key: %w", err)
	}

	sn, err := randomSerial()
	if err != nil {
		return "", "", err
	}

	now := time.Now()
	tmpl := &x509.Certificate{
		SerialNumber:          sn,
		Subject:               pkix.Name{CommonName: commonName, Organization: []string{"CVAP"}},
		NotBefore:             now.Add(-backdate),
		NotAfter:              now.Add(validFor),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLen:            0,
		MaxPathLenZero:        true,
	}

	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return "", "", fmt.Errorf("ca: self-sign: %w", err)
	}

	keyDER, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return "", "", fmt.Errorf("ca: marshal key: %w", err)
	}

	// Writes go through an os.Root scoped to dir (Go 1.24+), with fixed
	// filenames. Three properties, and each replaces something that was wrong or
	// merely asserted before:
	//
	//   os.WriteFile's permission argument applies only when it CREATES the
	//   file. Against a pre-existing ca.key at 0666 it wrote the key and left
	//   the mode alone — so the "written 0600" claim was false in exactly the
	//   case that mattered, and Open would then refuse to load what this had
	//   just written. O_EXCL makes it refuse instead, which is also what stops
	//   this silently replacing a live CA key: every certificate that key issued
	//   stops validating, and the previous key is gone.
	//
	//   os.Root confines every write beneath dir and refuses to traverse a
	//   symlink out of it. os.WriteFile followed one, so a planted link
	//   redirected the key somewhere readable.
	//
	//   The names passed to the root are constants, so there is no path for a
	//   caller to influence beyond the directory they already chose. That is
	//   also why gosec's G304 no longer fires: this is its own suggested fix
	//   rather than a suppression of it.
	root, err := os.OpenRoot(dir)
	if err != nil {
		return "", "", fmt.Errorf("ca: open target directory: %w", err)
	}
	defer func() { _ = root.Close() }()

	if err := writeNew(root, "ca.crt", pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), 0o644); err != nil {
		return "", "", fmt.Errorf("ca: write certificate: %w", err)
	}
	if err := writeNew(root, "ca.key", pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER}), 0o600); err != nil {
		return "", "", fmt.Errorf("ca: write signing key: %w", err)
	}
	return filepath.Join(dir, "ca.crt"), filepath.Join(dir, "ca.key"), nil
}

// writeNew creates a file that must not already exist, at exactly the mode
// given, beneath root.
func writeNew(root *os.Root, name string, data []byte, perm os.FileMode) error {
	f, err := root.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, perm)
	if err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		// The close error is discarded on purpose: the write error is the one
		// that matters, and returning a close failure instead would hide it.
		_ = f.Close()
		return err
	}
	return f.Close()
}
